
from aiogram.fsm.state import State, StatesGroup

class Steps(StatesGroup):
    width = State()
    length = State()
    terrace_exists = State()
    terrace_width = State()
    terrace_length = State()
    terrace_railings = State()
    first_floor_rooms = State()
    first_floor_height = State()
    first_floor_windows = State()
    second_floor_exists = State()
    second_floor_height = State()
    second_floor_full_height = State()
    second_floor_attic_height = State()
    second_floor_windows = State()
    second_floor_rooms = State()
    balcony_exists = State()
    roof_type = State()
    roof_angle = State()
    fronton_type = State()
    foundation_type = State()
    house_material = State()
    log_diametr = State()
    output_of_values = State()
    profiled_timber_width = State()
    profiled_timber_height = State()
    profiled_timber_row_height = State()
    planed_timber_width = State()
    planed_timber_height = State()
    roof_overhangs = State()
    roof_area = State()